### ISSUE TITLE
Version 1.1.1 not working

### ISSUE THREAD

**Issue by silver0346** [borgstrom/django-simple-menu#38]
Hi,

after update from version 1.1.0 to 1.1.1 I got issue:

'tuple' object has no attribute 'sort'

How I have to change menu configuration. And please change documentation. I think is the same like in version 1.1.0.

THX

**Comment by borgstrom** [comment]
Hi,

Can you please include a full trace back so I can see where the exception is coming from?

Thanks,
EB

**Comment by silver0346** [comment]
Hi,

I hope this is helpful.

==snipp==
2015-11-21 06:32:17 ERROR    django.request - base.py - handle_uncaught_exception [Internal Server Error: /login/]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/usr/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/lib/python2.7/site-packages/menu/templatetags/menu.py", line 16, in render
    menus = Menu.process(context['request'])
  File "/usr/lib/python2.7/site-packages/menu/menu.py", line 102, in process
    items[name] = c.process(request, name)
  File "/usr/lib/python2.7/site-packages/menu/menu.py", line 110, in process
    item.process(request)
  File "/usr/lib/python2.7/site-packages/menu/menu.py", line 213, in process
    self.children.sort(key=lambda child: child.weight)
AttributeError: 'tuple' object has no attribute 'sort'
==snapp==

**Comment by borgstrom** [comment]
Thanks.  This makes complete sense, the examples and documentation show using a tuple for the children while the tests all use lists.

I'll have a fix up for this shortly.
